language: cpp
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - travis_retry sudo add-apt-repository -y ppa:named-data/ppa
  - travis_retry sudo apt-get update -qq
  - travis_retry sudo apt-get install -qq ndnx-dev
  - travis_retry sudo apt-get install -qq libboost-all-dev
  - travis_retry sudo apt-get install -qq libcrypto++-dev
  - travis_retry sudo apt-get install -qq libsqlite3-dev
script:
  - ./waf configure --with-tests
  - ./waf
  - sudo ./waf install
  - sudo ldconfig
  - #
  - # Some tests now require daemon to run (and daemon needs the library to be compiled)
  - travis_retry git clone git://github.com/cawka/ndnd-tlv ndnd-tlv
  - cd ndnd-tlv
  - ./waf configure
  - ./waf -j1
  - sudo ./waf install
  - cd ..
  - #
  - #
  - ndnd-tlv-start
  - sleep 1
  - #
  - ./build/tests/unit-tests -l all
